### ISSUE TITLE
Unable to load the .pth files?

### ISSUE THREAD

**Issue by VSehwag** [locuslab/convex_adversarial#10]
It appears that somehow the provided '.pth' model files are not compatible with torch.load() method.  With torch 0.4.0 and python 2.7/3.6 the following command results in a _'UnpicklingError: invalid load key_' error.
--> _pytorch_network.load_state_dict(torch.load('mnist.pth')_

where pytorch_network is the model described in the paper. My impression is that pickle files run into issues when saved and loaded on different platforms. Can you please describe which platform (python & torch versions)  is used to generate these files?

**Comment by riceric22** [comment]
It's _might_ because those were saved using PyTorch 0.2, I'll be able to verify this later this weekend.

**Comment by riceric22** [comment]
Sorry for the delay, I've verified that the model files load properly with Python 3.6 using 0.4.0 on a Ubuntu 16.04 system using `torch.load()`. Are you by any chance using a different OS?
