### ISSUE TITLE
cannot import name robust_loss_batch

### ISSUE THREAD

**Issue by hope-yao** [locuslab/convex_adversarial#18]
Hi,

This is really a nice work and many thanks for making this code public! 

I got the following error when I was trying to run the 2D.ipynb. Could you please let me know if there is an additional file that is not committed to Github? Thanks again!

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-10-d518ed20108d> in <module>()
      1 import sys
      2 sys.path.append("../")
----> 3 from convex_adversarial import robust_loss_batch
      4 
      5 torch.manual_seed(1)

ImportError: cannot import name robust_loss_batch

**Comment by riceric22** [comment]
Hello! The 2D notebook example is a little out of date. Just rename all instances of robust_loss_batch to robust_loss and it will work (there was no need for the unbatched version anymore). I'll leave this issue open until the notebook is updated. 

~Eric

**Comment by hope-yao** [comment]
Cool! Thanks for the quick response!
