### ISSUE TITLE
CIFAR pretrained model?

### ISSUE THREAD

**Issue by chenhongge** [locuslab/convex_adversarial#19]
Hi Eric,
Could you please provide us with the CIFAR pretrained model? It seems that you have CIFAR training code here but I was not able to find the CIFAR model under models/ directory.
Thanks!

**Comment by riceric22** [comment]
Hey @chenhongge!

I'm in the middle of preparing a repository update to coincide with the second paper which includes the CIFAR models, which should be done by the start of next week. If you need something sooner, feel free to send me an email and I can send you some model weights. 

~Eric
