### ISSUE TITLE
Training using examples/mnist.py appears to get stuck - with default configuration and various other configurations

### ISSUE THREAD

**Issue by kaixiao** [locuslab/convex_adversarial#2]
I'm on the most recent commit of the master branch. I ran `examples/mnist.py` using the default configurations, and the training appears to be stuck in the first few epochs - the robust loss and regular loss both hover around 2.3, and the robust and regular error are always equal (around 0.9).

I tried a few different configurations, with varying success. By "success," I mean that training decreases the loss to well below 2 in the first epoch. Here are some examples of what worked/what didn't.

These work (usually, these succeed within a few hundred batches of the first epoch):
`python examples/mnist.py --batch_size 30 --epsilon 0.01`
`python examples/mnist.py --batch_size 30 --epsilon 0.03`
`python examples/mnist.py --batch_size 30 --epsilon 0.05`

These don't work:
`python examples/mnist.py --batch_size 30 --epsilon 0.09`
`python examples/mnist.py --batch_size 30 --epsilon 0.1`
`python examples/mnist.py`

Do you know whether something is going wrong with training for the default configuration?

**Comment by riceric22** [comment]
Hi kaixiao, 

Thanks for pointing this out. This phenomenon is actually described in section B2 in the appendix of our paper, where we found that for MNIST, if epsilon is initially large, there is a chance that the random initialization won't converge. 

We know of two ways to deal with this: 
1) less reliable, but using different random seeds can result in convergence, however we do not recommend this. 
2) very reliable, using an epsilon schedule which starts epsilon at a smaller value (in this case, 0.05), and gradually increase it over epochs. 

We found that the second method was able to converge in all scenarios where the initial random seed failed. This functionality is actually within `example/mnist.py` with the argument `--starting_epsilon` but I forgot to change the default value for this in the example code. I've fixed this with a8a19696f46ce4daf2a6a868c41da86c08f81192 but you can also just specify -starting_epsilon 0.05 to get the same result.

**Comment by kaixiao** [comment]
Thank you!
