### ISSUE TITLE
Loading the state_dict for a model

### ISSUE THREAD

**Issue by and-lap** [locuslab/convex_adversarial#29]
When trying to load one of the pre-trained models like this:

`robust_model.load_state_dict(torch.load('models_scaled_l2/mnist_large.pth')['state_dict'])`

I get this error:

`AttributeError: 'list' object has no attribute 'keys'`

Where `torch.load('models_scaled_l2/mnist_large.pth')['state_dict']` returns a list of length 6 dictionaries. Am I missing something in how to properly load a pre-trained model?

**Comment by riceric22** [comment]
Hello, the list is a sequence of cascaded models as described in https://arxiv.org/abs/1805.12514

If you wish for just the single model, then just use the first statedict in the list (e.g. element 0)

~Eric
