### ISSUE TITLE
`.pth` files not available

### ISSUE THREAD

**Issue by vtjeng** [locuslab/convex_adversarial#3]
The [`mnist_epsilon`](https://github.com/locuslab/convex_adversarial/blob/master/examples/mnist_epsilon.py#L36-L44) and [`primal`](https://github.com/locuslab/convex_adversarial/blob/master/examples/primal.py#L39-L47) examples make reference to files that aren't available (likely because of the [`gitignore`](https://github.com/locuslab/convex_adversarial/blob/master/.gitignore)). Are these files available elsewhere?

**Comment by riceric22** [comment]
Sure, I will make these available (and all other model files used in the paper, the ones mentioned in these files are only a subset and I was just changing the filenames to test different models).
