### ISSUE TITLE
PGD attack error

### ISSUE THREAD

**Issue by jhss** [locuslab/convex_adversarial#34]
I would like to evaluate the PGD error, so I uncommented the following line in trainer.py

```python
110  _,pgd_err = _pgd(model, Variable(X), Variable(y), epsilon)
```
Then, I ran the mnist.py, and get the following error

> Traceback (most recent call last):
>   File "examples/mnist.py", line 136, in <module>
>     err = evaluate_robust(test_loader, model[0], args.epsilon,
>   File "/data1/home/research/adversarial/convex_temp/convex_adversarial/examples/trainer.py", line 129, in evaluate_robust
>     _,pgd_err = _pgd(model, Variable(X), Variable(y), epsilon)
>   File "/data1/home/research/adversarial/convex_temp/convex_adversarial/examples/attacks.py", line 46, in _pgd
>     loss.backward()
>   File "/data1/home/anaconda3/envs/torch/lib/python3.8/site-packages/torch/tensor.py", line 198, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/data1/home/anaconda3/envs/torch/lib/python3.8/site-packages/torch/autograd/__init__.py", line 98, in backward
>     Variable._execution_engine.run_backward(
> RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

How can I solve the problem?

**Comment by riceric22** [comment]
In line 98 gradients are disabled. You'll need to re-enable gradients before running the PGD attack implemented within this repository (i.e. using `torch.enable_grad()` or re-enabling gradients within that function)
